<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Clear all watch history_yt-spec-touch-f_a713d7</name>
   <tag></tag>
   <elementGuidId>860f92d2-0869-4d00-a8d2-7e091007dbac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.yt-spec-button-shape-next.yt-spec-button-shape-next--text.yt-spec-button-shape-next--mono.yt-spec-button-shape-next--size-m.yt-spec-button-shape-next--icon-leading > yt-touch-feedback-shape > div.yt-spec-touch-feedback-shape.yt-spec-touch-feedback-shape--touch-response > div.yt-spec-touch-feedback-shape__fill</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='contents']/ytd-button-renderer/yt-button-shape/button/yt-touch-feedback-shape/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Clear all watch history&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>679959f1-ac4d-451d-a723-a9ea18329963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>yt-spec-touch-feedback-shape__fill</value>
      <webElementGuid>e88bab2e-1ffc-48c7-804b-84cedcda1ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-manager&quot;)/ytd-browse[@class=&quot;style-scope ytd-page-manager&quot;]/ytd-two-column-browse-results-renderer[@class=&quot;style-scope ytd-browse grid grid-4-columns&quot;]/div[@id=&quot;secondary&quot;]/ytd-browse-feed-actions-renderer[@class=&quot;style-scope ytd-two-column-browse-results-renderer&quot;]/div[@id=&quot;contents&quot;]/ytd-button-renderer[@class=&quot;style-scope ytd-browse-feed-actions-renderer&quot;]/yt-button-shape[1]/button[@class=&quot;yt-spec-button-shape-next yt-spec-button-shape-next--text yt-spec-button-shape-next--mono yt-spec-button-shape-next--size-m yt-spec-button-shape-next--icon-leading&quot;]/yt-touch-feedback-shape[1]/div[@class=&quot;yt-spec-touch-feedback-shape yt-spec-touch-feedback-shape--touch-response&quot;]/div[@class=&quot;yt-spec-touch-feedback-shape__fill&quot;]</value>
      <webElementGuid>b409bd08-00ff-4c26-b296-64f88af63920</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contents']/ytd-button-renderer/yt-button-shape/button/yt-touch-feedback-shape/div/div[2]</value>
      <webElementGuid>a5603a88-bf96-4517-9527-db10820bd75d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ytd-browse-feed-actions-renderer/div/ytd-button-renderer/yt-button-shape/button/yt-touch-feedback-shape/div/div[2]</value>
      <webElementGuid>695f4525-4178-4c01-8d97-670667f4dce9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
