<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_DSA</name>
   <tag></tag>
   <elementGuidId>dc153422-3594-46dd-8022-393b856dded7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2) > a.link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='secondarySubHeader']/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#secondarySubHeader >> internal:role=link[name=&quot;DSA&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4bc86fb4-39a9-4d18-afa9-2486a5db7e95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.geeksforgeeks.org/learn-data-structures-and-algorithms-dsa-tutorial/</value>
      <webElementGuid>b55bd659-4aee-4ad6-b450-f84ddd428a62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>32c16eb6-36c6-4a24-a1d2-75e5816589ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DSA</value>
      <webElementGuid>ca66551f-acc2-45ee-a161-f3be565dbae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;secondarySubHeader&quot;)/ul[@class=&quot;containerSubheader&quot;]/li[2]/a[@class=&quot;link&quot;]</value>
      <webElementGuid>c361553f-9dea-47ea-a4dd-c8609cdfe55e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='secondarySubHeader']/ul/li[2]/a</value>
      <webElementGuid>087a1c23-06b2-4948-9e59-949100ffd45f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'DSA')])[2]</value>
      <webElementGuid>8a17d9b6-6778-42ea-a75e-81528649c8ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trending Now'])[1]/following::a[1]</value>
      <webElementGuid>0c2fcec0-cb53-4318-b0df-7950c3d83e64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Language'])[1]/following::a[2]</value>
      <webElementGuid>9e2766fb-40b9-4d65-a199-d94f76268cc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Web Tech'])[1]/preceding::a[1]</value>
      <webElementGuid>f20330c2-3d8c-4d89-b3cc-59bfd5928f86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Foundational Courses'])[1]/preceding::a[2]</value>
      <webElementGuid>830e1888-caa5-4b77-a35a-6f170a3ccb0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DSA']/parent::*</value>
      <webElementGuid>840d9b1d-af08-4d0b-9c12-3ce419fc2e1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.geeksforgeeks.org/learn-data-structures-and-algorithms-dsa-tutorial/')])[2]</value>
      <webElementGuid>606ddf09-1fd7-456c-a01f-a1dcc93f414b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[2]/a</value>
      <webElementGuid>a307506a-7def-43c0-8e6c-4c9bba005617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.geeksforgeeks.org/learn-data-structures-and-algorithms-dsa-tutorial/' and (text() = 'DSA' or . = 'DSA')]</value>
      <webElementGuid>bc4716b3-7c6d-4cf3-8326-84ac474fc839</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
