<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Machine Learning Tutorial</name>
   <tag></tag>
   <elementGuidId>c2c73f1b-a0db-4d26-9477-dd55e2ec2f22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-1268561']/div[2]/div/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Machine Learning Tutorial&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>f7babd27-9f19-49da-855c-ea6de4a25ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Machine Learning Tutorial</value>
      <webElementGuid>47f58926-4876-4a50-ba66-a8cb405dce57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-1268561&quot;)/div[@class=&quot;main_wrapper&quot;]/div[1]/div[@class=&quot;article-title&quot;]/h1[1]</value>
      <webElementGuid>60e8f7f4-c310-49f2-9cff-0c397e5fe91b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-1268561']/div[2]/div/div/h1</value>
      <webElementGuid>835a9ddd-4469-4a80-b069-be705e990529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Course'])[1]/following::h1[1]</value>
      <webElementGuid>cf10ea91-d026-4ebd-9690-6611d2be699a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Updated :'])[1]/preceding::h1[1]</value>
      <webElementGuid>a60885a7-dfa1-4e14-bb02-e8fa1e2004aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Summarize'])[1]/preceding::h1[1]</value>
      <webElementGuid>51761c58-16bf-4fcc-a31f-f8205c63ad02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>67340042-07a0-4edf-8b3f-e7a4e3df013c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Machine Learning Tutorial' or . = 'Machine Learning Tutorial')]</value>
      <webElementGuid>685299a8-7f36-4059-a4c5-ed1edb1b1807</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
