<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Python Tutorial  Learn Python Programmin_fa9edc</name>
   <tag></tag>
   <elementGuidId>ac0b8cc0-a473-4d91-bd82-f3d758386bcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-1179442']/div[2]/div/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Python Tutorial | Learn Python Programming Language&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>ecf7a86e-5cb9-4a65-816b-d939483b50a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Python Tutorial | Learn Python Programming Language</value>
      <webElementGuid>db47e822-e0b3-43fa-b4e1-d14afb6173cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-1179442&quot;)/div[@class=&quot;main_wrapper&quot;]/div[1]/div[@class=&quot;article-title&quot;]/h1[1]</value>
      <webElementGuid>e8aa12b8-a21d-4c5f-bd32-552284fb31f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-1179442']/div[2]/div/div/h1</value>
      <webElementGuid>a71f69fd-0328-4614-90a1-0eb119a00904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Course'])[1]/following::h1[1]</value>
      <webElementGuid>6ec9e395-fffd-49a9-9eb9-1f4b14734180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Updated :'])[1]/preceding::h1[1]</value>
      <webElementGuid>5640acfa-0020-46bc-b4b5-6d452515df79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Summarize'])[1]/preceding::h1[1]</value>
      <webElementGuid>b337d625-098b-4504-a17d-b3241dab4096</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>7796aa5e-1c22-4301-89e3-b20753f5557f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Python Tutorial | Learn Python Programming Language' or . = 'Python Tutorial | Learn Python Programming Language')]</value>
      <webElementGuid>4d3efc74-a59d-42c5-899e-c84171e92996</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
